### ISSUE TITLE
Disable Single-Instance App/Files in Settings

### ISSUE THREAD

**Issue by Sensei412** [NX-Editor/NX-Editor#27]
The ability to compare two files of the same name within one instance or be able to open multiple instances of the application. Either of these would be nice to have. If the multiple instances is doable, idk how.

**Comment by ArchLeaders** [comment]
Both of those are the default actually, I added single-instance and single-file stuff as a feature. I can add settings to disable them though.

**Comment by ArchLeaders** [comment]
It's possible, not something I have time to implement though
